//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationDB.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryWorkExecution
    {
        public int Id { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual LaboratoryWork LaboratoryWork { get; set; }
    }
}
