//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationDB.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaboratoryWork()
        {
            this.LaboratoryWorkExecutions = new HashSet<LaboratoryWorkExecution>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryWorkExecution> LaboratoryWorkExecutions { get; set; }
    }
}
